name: JHapy Tree Flow  CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - run: echo Build for SHA = ${{ github.event.client_payload.sha }}, REF = ${{ github.event.client_payload.ref }}
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
      - name: Set up JDK 1.16
        uses: actions/setup-java@v1
        with:
          java-version: 1.16
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/jhapy/**
          key: ${{ runner.os }}-maven-tree-flow
          restore-keys: |
            ${{ runner.os }}-maven-tree-flow
      - name: Build with Maven
        run: mvn -Dmaven.test.skip -s .settings.xml -Dmaven.javadoc.skip -Dossrh_username=${{secrets.ossrh_username}} -Dossrh_password=${{secrets.ossrh_password}} --file pom.xml deploy
      - name: Workflow Dispatch to app-frontend-application repository
        uses: benc-uk/workflow-dispatch@v1
        with:
          repo: jhapy/app-frontend-application
          token: ${{ secrets.repos_access_token }}
          workflow: JHapy App Frontend Application CI
      - name: Slack Success
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()